version: '3.9'

services:
  pgdb:
    image: postgresql:13-alpine
    container_name: pgdb
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data/pgdata
    volumes:
      - custome-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  custome-data:
