# Generated by Django 4.2.23 on 2025-08-29 06:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_remove_answer_user_id_alter_answer_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('f305ec31-67c1-4966-9c5d-b11cf8f23836')),
        ),
    ]
